# Generated by Django 4.2.30 on 2026-05-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_class', models.CharField(db_column='class', max_length=100)),
                ('sub_class', models.CharField(blank=True, db_column='sub_class', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('data_file', models.FileField(upload_to='srs/reference_imports/')),
                ('metadata_file', models.FileField(upload_to='srs/reference_imports/')),
                ('data_sha256', models.CharField(blank=True, max_length=255)),
                ('metadata_sha256', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True)),
                ('uploaded_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='referencesample',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='referencesamplemeasurement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referencedeposit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedeposit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedeposit',
            name='three_char_code',
            field=models.CharField(db_index=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='referencesamplemeasurement',
            name='analytical_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='referencedeposit',
            name='source',
            field=models.CharField(blank=True, default='OSNACA', max_length=255),
        ),
        migrations.AlterField(
            model_name='referencesample',
            name='source_dataset',
            field=models.CharField(blank=True, default='OSNACA', max_length=255),
        ),
        # NOTE: import_ref fields must be added BEFORE any constraints reference them.
        migrations.AddField(
            model_name='referencedeposit',
            name='import_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='srs.referenceimport'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='import_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='srs.referenceimport'),
        ),
        migrations.AddField(
            model_name='referencesamplemeasurement',
            name='import_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='srs.referenceimport'),
        ),
        migrations.AddIndex(
            model_name='referencesamplemeasurement',
            index=models.Index(fields=['element', 'value'], name='srs_referen_element_85878d_idx'),
        ),
        migrations.AddConstraint(
            model_name='referencedeposit',
            constraint=models.UniqueConstraint(fields=('name', 'three_char_code'), name='referencedeposit_name_threechar_uniq'),
        ),
        migrations.AddConstraint(
            model_name='referencesample',
            constraint=models.UniqueConstraint(fields=('import_ref', 'sample_code'), name='referencesample_import_samplecode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='referencesamplemeasurement',
            constraint=models.UniqueConstraint(fields=('reference_sample', 'element', 'analytical_method'), name='refmeasurement_sample_element_method_uniq'),
        ),
        migrations.AddConstraint(
            model_name='depositclassification',
            constraint=models.UniqueConstraint(fields=('deposit_class', 'sub_class'), name='depositclassification_class_subclass_uniq'),
        ),
    ]
