# Generated by Django 4.2.30 on 2026-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0002_depositclassification_mineral_referenceimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceimport',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
