# Generated by Django 4.2.30 on 2026-05-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0004_dataset_col_count_dataset_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_sample_code', models.CharField(blank=True, max_length=100)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(default='log_difference_similarity', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FullAnalysisMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('similarity_score', models.FloatField()),
                ('elements_used', models.JSONField(blank=True, default=list)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_matches', to='srs.fullanalysis')),
                ('reference_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_analysis_matches', to='srs.referencesample')),
            ],
            options={
                'ordering': ['rank', '-similarity_score'],
                'unique_together': {('full_analysis', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='FullAnalysisInputMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='ppm', max_length=50)),
                ('below_detection_limit', models.BooleanField(default=False)),
                ('detection_limit', models.FloatField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_analysis_input_measurements', to='srs.element')),
                ('full_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_measurements', to='srs.fullanalysis')),
            ],
            options={
                'ordering': ['element__symbol'],
                'unique_together': {('full_analysis', 'element')},
            },
        ),
    ]
