# Generated by Django 4.2.30 on 2026-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0009_remove_legacy_analysis_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullanalysis',
            name='algorithm_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='algorithm_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='projection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='reference_library_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='runtime_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='sample_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullanalysis',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fullanalysismatch',
            name='confidence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullanalysismatch',
            name='evidence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullanalysismatch',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
