# Generated by Django 4.2.30 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0010_add_envelope_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullanalysis",
            name="element_associations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
