# Generated by Django 4.2.30 on 2026-09-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0011_fullanalysis_element_associations"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeochemicalSignature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("sample", "Analysed sample"), ("composite", "Analysis composite")], max_length=20)),
                ("sample_index", models.IntegerField(default=-1)),
                ("sample_code", models.CharField(blank=True, max_length=100)),
                ("representative_method", models.CharField(max_length=30)),
                ("value_space", models.CharField(default="ppm", max_length=20)),
                ("elements", models.JSONField(default=list)),
                ("raw_vector", models.JSONField(default=dict)),
                ("vector", models.JSONField(default=dict)),
                ("imputed_elements", models.JSONField(default=list)),
                ("preprocessing", models.JSONField(default=dict)),
                ("pipeline_version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_analysis", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="signatures", to="srs.fullanalysis")),
            ],
            options={
                "ordering": ["sample_index", "kind"],
            },
        ),
        migrations.AddConstraint(
            model_name="geochemicalsignature",
            constraint=models.UniqueConstraint(fields=("full_analysis", "kind", "sample_index"), name="unique_analysis_signature"),
        ),
    ]
